#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface BUILD service
#   Valid for Ubuntu20.04
#
#---------------------------------------------------------------------

FROM ran-base:latest AS gnb-base

FROM ran-build:latest AS gnb-build


#start from scratch for target executable
FROM ubuntu:jammy AS oai-gnb
ARG BUILD_OPTION
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
        software-properties-common \
        procps \
        libsctp1 \
        libboost-chrono1.74.0 \
        libboost-date-time1.74.0 \
        libboost-filesystem1.74.0 \
        libboost-regex1.74.0 \
        libboost-serialization1.74.0 \
        libboost-thread1.74.0 \
        libboost-system1.74.0 \
        libboost-program-options1.74.0 \
        tzdata \
        libblas3 \
        libconfig9 \
        openssl \
        net-tools \
        iperf \
        iperf3 \
        iproute2 \
        iputils-ping \
        gdb \
        python3 \
        python3-six \
        python3-requests \
        libusb-1.0-0 \
        libyaml-cpp-dev && \
# if the --sanitize option was used to build, additional packages are required
    /bin/bash -c 'if [[ "$BUILD_OPTION" = "--sanitize" ]]; then DEBIAN_FRONTEND=noninteractive apt-get install --yes \
        #libasan5 \ # see below
        libubsan1 \
        liblapacke; fi' && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

# we select another compile (gcc-12) for compilation, requiring another libasan
# library version. Installing it above would install the wrong version. Hence,
# copy the right version from ran-build. When upgrading to Ubuntu24, install
# the correct one above!
COPY --from=gnb-build /usr/lib/x86_64-linux-gnu/libasan.so.8.0.0 /usr/lib/x86_64-linux-gnu/

WORKDIR /opt/oai-gnb/bin
COPY --from=gnb-build \
    /oai-ran/cmake_targets/ran_build/build/nr-softmodem ./
COPY ./docker/scripts/gnb_entrypoint.sh ./entrypoint.sh

COPY --from=gnb-build \
    /oai-ran/cmake_targets/ran_build/build/liboai_eth_transpro.so \
    /oai-ran/cmake_targets/ran_build/build/librfsimulator.so \
    /oai-ran/cmake_targets/ran_build/build/liboai_usrpdevif.so \
    /oai-ran/cmake_targets/ran_build/build/libcoding.so \
    /oai-ran/cmake_targets/ran_build/build/libparams_libconfig.so \
    /oai-ran/cmake_targets/ran_build/build/libdfts.so \
    /oai-ran/cmake_targets/ran_build/build/libldpc*.so \
    /oai-ran/cmake_targets/ran_build/build/libtelnetsrv.so \
    /oai-ran/cmake_targets/ran_build/build/libtelnetsrv_ci.so \
    /oai-ran/cmake_targets/ran_build/build/libparams_yaml.so \
    /usr/local/lib/

# Now we are copying from builder-image the UHD files.
COPY --from=gnb-base /usr/local/bin/uhd_find_devices /usr/local/bin
COPY --from=gnb-base /usr/local/lib/libuhd.so.4.4.0 /usr/local/lib
COPY --from=gnb-base /usr/local/lib/uhd/utils/uhd_images_downloader.py /opt/oai-gnb/bin
## Copy E2 SM models
COPY --from=gnb-build /usr/local/lib/flexric /usr/local/lib/flexric

RUN /bin/bash -c "ln -s /usr/local/lib/liboai_usrpdevif.so /usr/local/lib/liboai_device.so" && \
    ldconfig && \
    echo "---- ldd on nr-softmodem ----" && \
    ldd /opt/oai-gnb/bin/nr-softmodem && \
    echo "---- ldd on shared libraries ----" && \
    ldd /usr/local/lib/liboai_eth_transpro.so \
        /usr/local/lib/librfsimulator.so \
        /usr/local/lib/liboai_usrpdevif.so \
        /usr/local/lib/libcoding.so \
        /usr/local/lib/libparams_libconfig.so \
        /usr/local/lib/libdfts.so \
        /usr/local/lib/libldpc*.so \
        /usr/local/lib/libtelnetsrv.so \
        /usr/local/lib/libtelnetsrv_ci.so \
        /usr/local/lib/libuhd.so.4.4.0

WORKDIR /opt/oai-gnb
#EXPOSE 2152/udp  # S1U, GTP/UDP
#EXPOSE 22100/tcp # ?
#EXPOSE 36412/udp # S1C, SCTP/UDP
#EXPOSE 36422/udp # X2C, SCTP/UDP
#EXPOSE 50000/udp # IF5 / ORI (control)
#EXPOSE 50001/udp # IF5 / ECPRI (data)

COPY --from=gnb-base /tini /tini
ENTRYPOINT ["/tini", "-v", "--", "/opt/oai-gnb/bin/entrypoint.sh"]
CMD ["/opt/oai-gnb/bin/nr-softmodem"]
