#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface 7.2 Fronthaul 
#      Valid for Rocky 9
#
#---------------------------------------------------------------------

FROM ran-base:latest AS gnb-base

FROM ran-build-fhi72:latest AS gnb-build

#start from scratch for target executable
FROM docker.io/rockylinux:9 AS oai-gnb-fhi72
ENV TZ=Europe/Paris

RUN dnf update -y && \
    dnf install -y \
        procps-ng \
        libXpm \
        libX11 \
        lksctp-tools \
        xz \
        numactl-libs \
        numactl-devel \
        pkg-config \
        pciutils \
        tzdata \
        gdb \
        python3 \
        python3-pip \
        net-tools \
        iputils && \
    pip3 install six && \
    pip3 install requests && \
    echo "/usr/local/lib" > /etc/ld.so.conf.d/local-lib.conf && \
    echo "/usr/local/lib64" >> /etc/ld.so.conf.d/local-lib.conf

WORKDIR /opt/oai-gnb/bin
COPY --from=gnb-build \
    /oai-ran/cmake_targets/ran_build/build/nr-softmodem ./
COPY ./docker/scripts/gnb_entrypoint.sh ./entrypoint.sh

COPY --from=gnb-build \
    /oai-ran/cmake_targets/ran_build/build/librfsimulator.so \
    /oai-ran/cmake_targets/ran_build/build/liboran_fhlib_5g.so \
    /oai-ran/cmake_targets/ran_build/build/liboai_transpro.so \
    /oai-ran/cmake_targets/ran_build/build/libcoding.so \
    /oai-ran/cmake_targets/ran_build/build/libparams_libconfig.so \
    /oai-ran/cmake_targets/ran_build/build/libdfts.so \
    /oai-ran/cmake_targets/ran_build/build/libldpc*.so \
    /oai-ran/cmake_targets/ran_build/build/libtelnetsrv.so \
    /oai-ran/cmake_targets/ran_build/build/libtelnetsrv_ci.so \
    /oai-ran/cmake_targets/ran_build/build/libparams_yaml.so \
    /usr/local/lib/

## Libxran library
COPY --from=gnb-build \
    /opt/phy/fhi_lib/lib/build/libxran.so \
    /opt/phy/fhi_lib/lib/build/

## Copy all DPDK libraries as liboran_fhlib_5g.so require most of them
COPY --from=gnb-build /usr/local/lib64/ /usr/local/lib64/

## Copy E2 SM models
COPY --from=gnb-build /usr/local/lib64/flexric /usr/local/lib64/flexric

# Copying file for configuration module
COPY --from=gnb-base \
    /lib64/libconfig.so.11 \
    /lib64/libforms.so.2 \
    /lib64/libblas.so.3 \
    /lib64/libcblas.so.3 \
    /lib64/liblapack.so.3 \
    /lib64/liblapacke.so.3 \
    /lib64/libicudata.so.67 \
    /lib64/libicui18n.so.67 \
    /lib64/libicuuc.so.67 \
    /lib64/

RUN ldconfig && \
    echo "---- ldd on executable nr-softmodem ----" && \
    ldd /opt/oai-gnb/bin/nr-softmodem && \
    echo "---- ldd on shared libraries ----" && \
    ldd /usr/local/lib/librfsimulator.so \
        /usr/local/lib/liboran_fhlib_5g.so \
        /usr/local/lib/liboai_transpro.so \
        /usr/local/lib/libcoding.so \
        /usr/local/lib/libparams_libconfig.so \
        /usr/local/lib/libdfts.so \
        /usr/local/lib/libldpc*.so \
        /usr/local/lib/libtelnetsrv.so \
        /usr/local/lib/libtelnetsrv_ci.so \
        /opt/phy/fhi_lib/lib/build/libxran.so

WORKDIR /opt/oai-gnb
COPY --from=gnb-base /tini /tini
ENTRYPOINT ["/tini", "-v", "--", "/opt/oai-gnb/bin/entrypoint.sh"]
CMD ["/opt/oai-gnb/bin/nr-softmodem"]
