#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface BUILD service
#   Valid for Ubuntu 22.04
#
#---------------------------------------------------------------------
FROM ubuntu:xenial AS oai-cppcheck


ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
       build-essential \
       vim \
       cppcheck

WORKDIR /oai-ran
COPY . .

WORKDIR /oai-ran/common/utils/T
RUN make

WORKDIR /oai-ran
RUN mkdir -p cmake_targets/log && \
    cppcheck --enable=warning --force --xml --xml-version=2 \
        --inline-suppr \
        -i openair1/PHY/CODING/nrLDPC_decoder/nrLDPC_decoder.c \
        --suppressions-list=ci-scripts/cppcheck_suppressions.list \
        -I common/utils \
        -I openair3/NAS/COMMON/UTIL \
        -j`nproc` . 2> cmake_targets/log/cppcheck.xml 1> cmake_targets/log/cppcheck_build.txt

RUN grep -E -c 'severity="error' cmake_targets/log/cppcheck.xml

RUN grep -E -c 'severity="warning' cmake_targets/log/cppcheck.xml

RUN cat cmake_targets/log/cppcheck.xml
